Doctor/urls.py
from django.urls import path 
from .import views
app_name='Doctor'

urlpatterns = [
    path('',views.index,name='index'),
    path('login',views.login,name='login'),
    path('signup',views.signup,name='signup')

]

admn/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('home1',views.home1)

]

hospitalmngmt/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Doctor/',include('Doctor.urls')),
    path('patient/',include('patient.urls')),
    path('admn/',include('admn.urls'))

]

patient/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('home',views.home)

]

Doctor/models.py
from django.db import models

# Create your models here.

admn/models.py
from django.db import models

# Create your models here.

patient/models.py
from django.db import models

# Create your models here.

Doctor/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
# def index(request):
#     return HttpResponse('this is doctor module')

def index(request):
    return render(request,'doctor_templates/home.html')


def login(request):
    return render(request,'doctor_templates/login.html')    

def signup(request):
    return render(request,'doctor_templates/sign_up.html')      

admn/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home1(request):
    return HttpResponse('admin home screen')

patient/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def home(request):
    return HttpResponse('patient home screen')

Doctor/templates/doctor_templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto unde maiores enim molestiae commodi ipsam mollitia tenetur quibusdam repellat, atque quis quae quam consequatur culpa. Ducimus natus repellat eaque mollitia.</h1>
    <img src="{% static 'images/OIP.jpg' %}" alt="">
    <p> this is the home page</p>
    <h1>this is for checking Git</h1>
</body>
</html>

Doctor/templates/doctor_templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <input type="text" placeholder="enter email">
    <input type="text" placeholder="enter password">
    <a href="{% url 'Doctor:index' %}"><button type="button">Login</button></a>

</body>
</html>

Doctor/templates/doctor_templates/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <input type="text" placeholder="enter username">
    <input type="text" placeholder="enter password">
    <input type="button" value="submit">
</body>
</html>